blank_issues_enabled: true
contact_links:
  - name: ğŸ¤” å•é¡Œ
    url: https://github.com/blackcatbot/blackcat
    about: ä½ å¯ä»¥é–‹å•ŸIssuesï¼Œæˆ‘å€‘å¾ˆå¿«å°±æœƒç‚ºæ‚¨æä¾›æ”¯æ´!
  - name: ğŸ’¬ èŠå¤©
    url: https://discord.gg/fumVBww
    about: æƒ³è¦èˆ‡å…¶ä»–äººè¨è«–é—œæ–¼æ©Ÿå™¨äººçš„è©±é¡Œå—ï¼ŸåŠ å…¥æˆ‘å€‘çš„ä¼ºæœå™¨å§!
